package group14.finalproject.mytodotask

// Name database
const val DATABASE_TASK_SUFFIX_NAME = "-NOTE.dbTasks"
const val DATABASE_TAG_SUFFIX_NAME = "-TAG.dbTasks"
const val DATABASE_RELATIONSHIP_SUFFIX_NAME = "-RELATIONSHIP.dbTasks"

// CODE FOR RESULT ACTIVITY
const val CODE_ADD_NEW_TASK = 1015
const val CODE_EDIT_TASK = 1016

// KEY FOR CHANGE DATA ACTIVITY
const val TASK_ID_KEY = "TASK_ID_KEY"
const val TASK_UPDATE_KEY = "TASK_UPDATE_KEY"
const val TASK_NEW_KEY = "TASK_NEW_KEY"
const val TASK_TITLE_KEY = "TASK_TITLE_KEY"
const val TASK_DESCRIPTION_KEY = "TASK_DESCRIPTION_KEY"
const val TASK_DATE_KEY = "TASK_DATE_KEY"
const val TASK_TIME_KEY = "TASK_TIME_KEY"
const val TASK_CHECK_KEY = "TASK_CHECK_KEY"
const val TASK_PRIORITY_KEY = "TASK_PRIORITY_KEY"
const val TASK_LOCATIONX_KEY = "TASK_LOCATIONX_KEY"
const val TASK_LOCATIONY_KEY = "TASK_LOCATIONY_KEY"
const val TASK_CATEGORIZED_KEY = "TASK_CATEGORIZED_KEY"
const val TASK_REMINDER_KEY = "TASK_REMINDER_KEY"
const val TASK_ATTACH_KEY = "TASK_ATTACH_KEY"

// CODE FOR POSITION
const val CODE_EDIT_TASK_POSITION = "CODE_EDIT_TASK_POSITION"
const val CODE_DELETE_TASK_POSITION = "CODE_DELETE_TASK_POSITION "

// SHARED PREFERENCES
const val USERNAME_KEY = "USERNAME_KEY"
const val PREFERENCES_NAME = "KHTN_PREF"
const val EMAIL_DEFAULT = "group14@gmail.com"

// SEARCH ACTIVITY
const val FLAG_TITLE = 0
const val FLAG_TAGS = 1
const val FLAG_COMPLETED = 21
const val FLAG_UNCOMPLETED = 22
const val FLAG_NONE = 23