package com.example.mainactivity

const val MOVIE_MODEL_KEY = "MOVIE_MODEL"
const val MOVIE_TITLE_KEY = "MOVIE_TITLE_KEY"
const val MOVIE_IMAGE_KEY = "MOVIE_IMAGE_KEY"
const val MOVIE_OVERVIEW_KEY = "MOVIE_OVERVIEW_KEY"
const val MOVIE_VOTE_COUNT_KEY = "MOVIE_VOTE_COUNT_KEY"
const val MOVIE_VIDEO_KEY = "MOVIE_VIDEO_KEY"
const val MOVIE_VOTE_AVERAGE_KEY = "MOVIE_VOTE_AVERAGE_KEY"
const val MOVIE_RELEASE_DATE_KEY = "MOVIE_RELEASE_DATE_KEY"