package com.example.week6

const val DATABASE_TASK_NAME = "NHOM14-APP-TASK.db"
const val DATABASE_USER_NAME = "NHOM14-APP-USER.db"
const val CODE_ADD_NEW_STUDENT = 1015
const val TASK_DESCRIPTION_KEY = "TASK_DESCRIPTION_KEY"
const val TASK_COMPLETED_KEY = "TASK_COMPLETED_KEY"
const val TASK_ASSIGNED_KEY = "TASK_ASSIGNED_KEY"
const val TASK_POSITION_KEY = "TASK_POSITION_KEY"
const val TASK_ID_KEY = "TASK_ID_KEY"
const val TASK_DELETE_KEY = "TASK_DELETE_KEY"